language: node_js
node_js:
  - "6"
sudo: false
before_install:
- export TZ=Asia/Taipei
- npm install -g hexo-cli
before_script:
- git config --global user.name 'jiaming0708'
- git config --global user.email 'jiaming0708@gmail.com'
- sed -i'' "s~git@github.com:jiaming0708/blog-source.git~https://${GH_TOKEN}@github.com/jiaming0708/jiaming0708.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo deploy --generate
cache:
  directories:
  - node_modules   
